Enable Ambient Sounds: true
Nether Lightning: true
Soulsand Slowness: true
Netherrack Fires: true
Enable Custom Mobs: true
Enable Mean Ghasts: true
Enable Lava Burns: true
Enable Lava Placement: true
Enable Lava Spouts: true
Enable Falling Nether: true
Enable Nether Structures: true
Enable Alpha Pigman Sword Drop: true
Wither Potion Drops: true
Haste Potion Drops: true
Extended Wither Boss: false
# Replaced enderdragon growl with an enderman growl
replace_enderdragon_growl: false
# Higher equals lower chance!
Lightning Chance: 0
Netherack Melting Chance: 18
Netherrack Fire Chance: 10
Mob Spawn Chance: 5
Falling Nether Chance: 0
Alpha Pigman Sword Drop Chance: 1
# Lower equals louder
Wind Volume: 800
# Must be between 0 and 2
Wind Pitch: 0
Low Y Value Wind: 70
High Y Value Wind: 200
Netherrack Step Sound: ENTITY_SLIME_SQUISH
Wither Potion Drop Chance: 2
Haste Potion Drop Chance: 2
### Structures
All Structures Chance: 0
Web Vine Chance: 0
Mushroom Chance: 0
Nether Spike Chance: 0
Nether World Height: 120
Coral Chance: 0
Rose Chance: 0
Mushrooms Chance: 0
Replace Netherrack Chance: 0
### Spawn Chance ###
Spawn Molten: true
Spawn Fireball: true
Spawn Inferno: true
Spawn Old Shadow: true
Spawn Sherogath: true
Spawn Sadness: true
Spawn Necromancer: true
Spawn Alpha Pigman: true
### Monster Names ###
Molten: "Molten"
Fireball: "Fireball"
Inferno: "Inferno"
Old_Shadow: "Old Shadow"
Sherogath: "Sherogath"
Sadness: "Sadness"
Necromancer: "Necromancer"
Alpha_Pigman: "Alpha Pigman"
### If Left Blank Will Just Use default world
Enabled Worlds:
  - world_nether
